classDiagram
    Usuario <|-- Paciente: hereda
    Usuario <|-- Administrador: hereda
    Usuario <|-- Especialista: hereda
    Turno <-- Estado: tiene 
    Paciente <-- fichaMedica: tiene 
    Paciente <-- HistoriaClinica: tiene
    Paciente <-- Turno: tiene 

    class Usuario {
        -String nombre
        -String apellido
        -String correo
        -String contraseña
        -Int telefono
        -String direccion
        -String ciudad
        -String pais
        -Date fechaNacimiento

        -crearCuenta()
        -login()
        -logout()
        -solicitarTurno()
        -cancelarTurno()
        -verHistoriaClinica()

    }


    class Turno {
        -Date fecha
        -Time hora
        -String especialista
        -String paciente
        -Estado estado

        -crearTurno()
        -confirmarTurno()
        -verTurno()
        -cancelarTurno()
        -reprogramarTurno()
    }

    class Estado {
        -String estado
        -String descripcion
    }

    class Paciente {
        -String nombre
        -String apellido
        -Int dni

        -verFichaMedica()
        -verHistoriaClinica()
        -verTurno()
        -solicitarTurno()
    }

    class Especialista {
        -String nombre
        -String apellido
        -String especialidad

        -verFichaMedica()
        -verHistoriaClinica()
    }


    class Administrador {
        -String nombre
        -String apellido
        -String correo
        -String contraseña
        -Int telefono
        -String direccion
        -String ciudad
        -String pais
        -Date fechaNacimiento

        -verFichaMedica()
        -verHistoriaClinica()
        -verTurno()
    }

    class fichaMedica {
        -Paciente paciente
        -Especialista especialista
        -Date fecha
        -String motivoConsulta
        -String antecedentes
        -String examenFisico
        -String diagnostico
        -String observaciones

        -crearFichaMedica()
        -verFichaMedica()
        -guardarFichaMedica()

    }

    class Medicameto {
        -String nombre
        -String descripcion
        -String dosis
        -String frecuencia
        -String duracion
    }

    class antecedentes {
        -String enfermedades
        -String alergias
        -String cirugias
        -String traumatismos
        -String hospitalizaciones
    }

    class examenFisico {
        -String peso
        -String altura
        -String temperatura
        -String presionArterial
        -String frecuenciaCardiaca
        -String frecuenciaRespiratoria
    }

    class diagnostico {
        -String diagnostico
        -String tratamiento
    }

    class HistoriaClinica {
        -Paciente paciente
        -Especialista especialista
        -Date fecha
        -String antecedentes
        -String examenFisico
        -String diagnostico
        -String observaciones
        -Medicameto medicameto

        
    }
