erDiagram
    Usuario {
        int idUsuario PK
        varchar nombre
        varchar apellido
        varchar correo
        varchar contrasenia
    }

    Paciente {
        int idPaciente PK
        int idUsuario FK
        int idDireccion FK
        varchar telefono
        date fechaNacimiento
        int dni
    }
    
    Administrador {
        int idAdministrador PK
        int idUsuario FK
    }
    
    Especialista {
        int idEspecialista PK
        int idUsuario FK
        int idEspecialidad FK
        int matricula
    }

    Especialidad {
        int idEspecialidad PK
        varchar especialidad
        text descripcion
    }
    
    Turno {
        int idTurno PK
        date fecha
        time hora
        int idEspecialista FK
        int idPaciente FK
        int idEstadoTurno FK
    }
    
    EstadoTurno {
        int idEstadoTurno PK
        varchar estado
        text descripcion
    }

    FichaMedica {
        int idFichaMedica PK
        int idPaciente FK
        int idEspecialista FK
        date fecha
        varchar motivoConsulta
        text examenFisico
        text diagnostico
        text observaciones
    }

    FichaPaciente {
        int idFichaPaciente PK
        int idUsuario FK
        float altura
        float peso
        text antecedentes
        int idObraSocial FK
        int idGrupoSanguineo FK
        int idAntecedentePrevio FK
    }
    
    AntecedentePrevio {
        int idAntecedentePrevio PK
        int idFichaPaciente FK
        varchar nombre
        text descripcion
        date fecha
    }

    GrupoSanguineo {
        int idGrupoSanguineo PK
        varchar Factor
        varchar Grupo
    }

    ObraSocial {
        int idObraSocial PK
        varchar nombre
        text descripcion
    }

    Direccion {
        int idDireccion PK
        varchar calle
        varchar numero
        varchar codigoPostal
        int idCiudad FK
    }

    Ciudad {
        int idCiudad PK
        varchar nombre
        int idProvincia FK
    }

    Provincia {
        int idProvincia PK
        varchar nombre
        int idPais FK
    }

    Pais {
        int idPais PK
        varchar nombre
    }
    
    HistoriaClinica {
        int idHistoriaClinica PK
        int idPaciente FK
        int idEspecialista FK
        date fecha
        text antecedentes
        text examenFisico
        text diagnostico
        text observaciones
        int idMedicamento FK
    }
    

    Usuario ||--o| Paciente : tiene
    Usuario ||--o| Administrador : tiene
    Usuario ||--o| Especialista : tiene
    Paciente ||--o{ Turno : tiene
    Especialista ||--o{ Turno : tiene
    Turno ||--o{ EstadoTurno : tiene
    Paciente ||--o{ FichaMedica : tiene
    Especialista ||--o{ FichaMedica : tiene
    Paciente ||--o{ HistoriaClinica : tiene
    Especialista ||--o{ HistoriaClinica : tiene
    Paciente ||--o{ FichaPaciente : tiene
    FichaPaciente ||--o| AntecedentePrevio : tiene
    FichaPaciente ||--o| GrupoSanguineo : tiene
    FichaPaciente ||--o| ObraSocial : tiene
    Especialista ||--o{ Especialidad : tiene
    Paciente ||--o{ Direccion : tiene
    Direccion ||--o| Ciudad : pertenece
    Ciudad ||--o| Provincia : pertenece
    Provincia ||--o| Pais : pertenece



    
